"""empty message

Revision ID: 16edaa6b893f
Revises: 3979ac504886
Create Date: 2017-12-25 08:29:38.641340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16edaa6b893f'
down_revision = '3979ac504886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'location')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
