"""empty message

Revision ID: 5dbea83c9cf9
Revises: 
Create Date: 2017-12-20 13:35:49.764952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dbea83c9cf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'users', ['password'], unique=True)
    # ### end Alembic commands ###
